Add test for varsub in secret
fluxcd/kustomize-controller pull request #505
Opened 2021-11-25 11:44 UTC by SomtochiAma

Fixes: #502 

Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

2021-11-26 09:29 UTC, stefanprodan requested changes

2021-11-26 09:29 UTC, stefanprodan commented on docs/spec/v1beta2/kustomization.md
> +```yaml
Add new line above this please.

2021-11-26 15:46 UTC, makkes approved these changes

2021-11-26 16:11 UTC, stefanprodan commented
@makkes I see that you've approved this PR, but the doc formatting is wrong, it will not render on fluxcd.io due to that empty line missing.

2021-11-26 16:49 UTC, makkes commented
> @makkes I see that you've approved this PR, but the doc formatting is wrong, it will not render on fluxcd.io due to that empty line missing.

Yeah, my usual way in these situations is to approve the PR and assume that prior change requests are properly addressed. Does that sound reasonable?

2021-11-26 16:51 UTC, stefanprodan commented
> Does that sound reasonable?

Yeap all good

2021-12-02 09:13 UTC, stefanprodan approved these changes

2021-12-02 09:13 UTC, merged